version: '3.8'
services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    environment:
      APP_NAME: Laravel
      APP_ENV: local
  db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: laravel # Name of the database
      MYSQL_USER: user # Non-root user
      MYSQL_PASSWORD: root # Password for non-root user
      MYSQL_ROOT_PASSWORD: root # Root password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
